
## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

In [2]:
#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN'], axis=1)
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Determine the number of unique values in each column.
unique_values = application_df.nunique()
unique_values

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [5]:
from pandas.core.arrays.interval import value_counts
# Look at APPLICATION_TYPE value counts for binning

app_counts = application_df['APPLICATION_TYPE'].value_counts()
app_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`


application_types_to_replace = list(app_counts[app_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Look at NAME value counts for binning

name_counts = application_df['NAME'].value_counts()
name_counts

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [8]:
name_counts[name_counts > 1]
name_counts

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [9]:
# Choose a cutoff value and create a list of names to be replaced
# use the variable name `names_to_replace`
names_to_replace = list(name_counts[name_counts < 100].index)

# Replace in dataframe
for nm in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(nm,"Other")
    
# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                                                 25987
PARENT BOOSTER USA INC                                                 1260
TOPS CLUB INC                                                           765
UNITED STATES BOWLING CONGRESS INC                                      700
WASHINGTON STATE UNIVERSITY                                             492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                         408
PTA TEXAS CONGRESS                                                      368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC                           331
ALPHA PHI SIGMA                                                         313
TOASTMASTERS INTERNATIONAL                                              293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS                       287
LITTLE LEAGUE BASEBALL INC                                              277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS                                266
MOMS CLUB                                                               210
INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION      206
AMERICAN ASSOCIATION OF UNIVERSITY WOMEN                                197
FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA                    166
KNIGHTS OF COLUMBUS                                                     158
HABITAT FOR HUMANITY INTERNATIONAL INC                                  154
TENNESSEE ORDER OF THE EASTERN STAR                                     151
VETERANS OF FOREIGN WARS OF THE UNITED STATES AUXILIARY                 144
PTA UTAH CONGRESS                                                       140
THE UNITED STATES PONY CLUBS INC                                        136
CIVITAN INTERNATIONAL                                                   131
SIGMA BETA DELTA INC                                                    127
HONOR SOCIETY OF PHI KAPPA PHI                                          107
MONTANA 4-H FOUNDATION INC                                              107
WASHINGTON STATE GRANGE                                                 106
UNIVERSITY OF WYOMING                                                   105
DEMOLAY INTERNATIONAL                                                   104
SERTOMA INC                                                             103
Name: NAME, dtype: int64

In [10]:
# Look at AFFILIATION value counts for binning

affiliation_counts = application_df['AFFILIATION'].value_counts()
affiliation_counts

Independent         18480
CompanySponsored    15705
Family/Parent          64
National               33
Regional               13
Other                   4
Name: AFFILIATION, dtype: int64

In [11]:
# Choose a cutoff value and create a list of affiliations to be replaced
# use the variable name `affiliations_to_replace`


affiliations_types_to_replace = list(affiliation_counts[affiliation_counts < 60].index)

# Replace in dataframe
for affi in affiliations_types_to_replace:
    application_df['AFFILIATION'] = application_df['AFFILIATION'].replace(affi,"Other")

# Check to make sure binning was successful
application_df['AFFILIATION'].value_counts()

Independent         18480
CompanySponsored    15705
Family/Parent          64
Other                  50
Name: AFFILIATION, dtype: int64

In [12]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [13]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts[classification_counts > 1]
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [14]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_counts[classification_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [15]:
# Convert categorical data to numeric with `pd.get_dummies`
numeric_dummies = pd.get_dummies(application_df)

In [16]:
numeric_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_ALPHA PHI SIGMA,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES INC,NAME_AMERICAN ASSOCIATION OF UNIVERSITY WOMEN,NAME_CIVITAN INTERNATIONAL,NAME_DEMOLAY INTERNATIONAL,NAME_FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA,NAME_HABITAT FOR HUMANITY INTERNATIONAL INC,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [17]:
# Split our preprocessed data into our features and target arrays
y = numeric_dummies['IS_SUCCESSFUL'].values

X = numeric_dummies.drop(columns='IS_SUCCESSFUL').values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=42)

In [18]:
# Create a StandardScaler instances
scaler = StandardScaler()

In [19]:
# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

In [20]:
# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [21]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
num_input_features = X_train_scaled.shape[1]
print(f"num_input_features : {num_input_features}")
# num of input features is 72 and multiple (2 or 3) of input feature is 144-216, chose 90 for the first hidden node
hidden_node_1 = 90
hidden_node_2 = 30
hidden_node_3 = 20

nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_node_1, activation="relu", input_dim=num_input_features))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_node_2, activation="relu"))

# Third hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_node_3, activation="relu"))


# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

num_input_features : 72
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 90)                6570

 dense_1 (Dense)             (None, 30)                2730

 dense_2 (Dense)             (None, 20)                620

 dense_3 (Dense)             (None, 1)                 21

=================================================================
Total params: 9,941
Trainable params: 9,941
Non-trainable params: 0
_________________________________________________________________

In [22]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [23]:
# Train the model
fit_model = nn_model.fit(X_train_scaled,y_train,epochs=110)

Epoch 1/110
804/804 [==============================] - 3s 2ms/step - loss: 0.5102 - accuracy: 0.7456
Epoch 2/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4939 - accuracy: 0.7573
Epoch 3/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4889 - accuracy: 0.7584
Epoch 4/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4878 - accuracy: 0.7598
Epoch 5/110
804/804 [==============================] - 3s 3ms/step - loss: 0.4861 - accuracy: 0.7608
Epoch 6/110
804/804 [==============================] - 3s 4ms/step - loss: 0.4857 - accuracy: 0.7620
Epoch 7/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4849 - accuracy: 0.7603
Epoch 8/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4839 - accuracy: 0.7608
Epoch 9/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4831 - accuracy: 0.7614
Epoch 10/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4830 - accuracy: 0.7615
Epoch 11/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4819 - accuracy: 0.7623
Epoch 12/110
804/804 [==============================] - 2s 3ms/step - loss: 0.4818 - accuracy: 0.7632
Epoch 13/110
804/804 [==============================] - 3s 3ms/step - loss: 0.4812 - accuracy: 0.7623
Epoch 14/110
804/804 [==============================] - 2s 3ms/step - loss: 0.4807 - accuracy: 0.7633
Epoch 15/110
804/804 [==============================] - 2s 3ms/step - loss: 0.4801 - accuracy: 0.7656
Epoch 16/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4802 - accuracy: 0.7631
Epoch 17/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4793 - accuracy: 0.7639
Epoch 18/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4789 - accuracy: 0.7640
Epoch 19/110
804/804 [==============================] - 3s 3ms/step - loss: 0.4787 - accuracy: 0.7634
Epoch 20/110
804/804 [==============================] - 3s 3ms/step - loss: 0.4787 - accuracy: 0.7644
Epoch 21/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4781 - accuracy: 0.7650
Epoch 22/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4781 - accuracy: 0.7645
Epoch 23/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4781 - accuracy: 0.7655
Epoch 24/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4776 - accuracy: 0.7645
Epoch 25/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4774 - accuracy: 0.7663
Epoch 26/110
804/804 [==============================] - 3s 3ms/step - loss: 0.4766 - accuracy: 0.7648
Epoch 27/110
804/804 [==============================] - 3s 3ms/step - loss: 0.4764 - accuracy: 0.7654
Epoch 28/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4761 - accuracy: 0.7664
Epoch 29/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4759 - accuracy: 0.7656
Epoch 30/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4764 - accuracy: 0.7648
Epoch 31/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4757 - accuracy: 0.7661
Epoch 32/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4759 - accuracy: 0.7657
Epoch 33/110
804/804 [==============================] - 2s 3ms/step - loss: 0.4757 - accuracy: 0.7668
Epoch 34/110
804/804 [==============================] - 3s 3ms/step - loss: 0.4751 - accuracy: 0.7671
Epoch 35/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4749 - accuracy: 0.7668
Epoch 36/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4750 - accuracy: 0.7671
Epoch 37/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4746 - accuracy: 0.7667
Epoch 38/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4746 - accuracy: 0.7665
Epoch 39/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4743 - accuracy: 0.7677
Epoch 40/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4741 - accuracy: 0.7664
Epoch 41/110
804/804 [==============================] - 3s 3ms/step - loss: 0.4737 - accuracy: 0.7676
Epoch 42/110
804/804 [==============================] - 2s 3ms/step - loss: 0.4737 - accuracy: 0.7671
Epoch 43/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4740 - accuracy: 0.7675
Epoch 44/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4734 - accuracy: 0.7672
Epoch 45/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4729 - accuracy: 0.7681
Epoch 46/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4729 - accuracy: 0.7674
Epoch 47/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4732 - accuracy: 0.7681
Epoch 48/110
804/804 [==============================] - 3s 3ms/step - loss: 0.4733 - accuracy: 0.7682
Epoch 49/110
804/804 [==============================] - 3s 4ms/step - loss: 0.4730 - accuracy: 0.7668
Epoch 50/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4726 - accuracy: 0.7682
Epoch 51/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4729 - accuracy: 0.7672
Epoch 52/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4724 - accuracy: 0.7680
Epoch 53/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4726 - accuracy: 0.7675
Epoch 54/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4723 - accuracy: 0.7683
Epoch 55/110
804/804 [==============================] - 3s 3ms/step - loss: 0.4724 - accuracy: 0.7684
Epoch 56/110
804/804 [==============================] - 3s 3ms/step - loss: 0.4723 - accuracy: 0.7682
Epoch 57/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4716 - accuracy: 0.7674
Epoch 58/110
804/804 [==============================] - 2s 3ms/step - loss: 0.4717 - accuracy: 0.7669
Epoch 59/110
804/804 [==============================] - 3s 3ms/step - loss: 0.4716 - accuracy: 0.7680
Epoch 60/110
804/804 [==============================] - 2s 3ms/step - loss: 0.4716 - accuracy: 0.7678
Epoch 61/110
804/804 [==============================] - 3s 3ms/step - loss: 0.4715 - accuracy: 0.7674
Epoch 62/110
804/804 [==============================] - 3s 3ms/step - loss: 0.4715 - accuracy: 0.7687
Epoch 63/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4717 - accuracy: 0.7680
Epoch 64/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4713 - accuracy: 0.7687
Epoch 65/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4715 - accuracy: 0.7681
Epoch 66/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4709 - accuracy: 0.7682
Epoch 67/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4713 - accuracy: 0.7679
Epoch 68/110
804/804 [==============================] - 3s 3ms/step - loss: 0.4707 - accuracy: 0.7683
Epoch 69/110
804/804 [==============================] - 3s 3ms/step - loss: 0.4713 - accuracy: 0.7680
Epoch 70/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4703 - accuracy: 0.7684
Epoch 71/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4711 - accuracy: 0.7690
Epoch 72/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4708 - accuracy: 0.7683
Epoch 73/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4713 - accuracy: 0.7689
Epoch 74/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4707 - accuracy: 0.7686
Epoch 75/110
804/804 [==============================] - 2s 3ms/step - loss: 0.4705 - accuracy: 0.7675
Epoch 76/110
804/804 [==============================] - 3s 3ms/step - loss: 0.4708 - accuracy: 0.7680
Epoch 77/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4707 - accuracy: 0.7691
Epoch 78/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4705 - accuracy: 0.7687
Epoch 79/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4702 - accuracy: 0.7690
Epoch 80/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4703 - accuracy: 0.7687
Epoch 81/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4699 - accuracy: 0.7685
Epoch 82/110
804/804 [==============================] - 2s 3ms/step - loss: 0.4699 - accuracy: 0.7681
Epoch 83/110
804/804 [==============================] - 3s 3ms/step - loss: 0.4696 - accuracy: 0.7690
Epoch 84/110
804/804 [==============================] - 2s 3ms/step - loss: 0.4699 - accuracy: 0.7684
Epoch 85/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4698 - accuracy: 0.7687
Epoch 86/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4698 - accuracy: 0.7693
Epoch 87/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4698 - accuracy: 0.7690
Epoch 88/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4694 - accuracy: 0.7691
Epoch 89/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4697 - accuracy: 0.7694
Epoch 90/110
804/804 [==============================] - 2s 3ms/step - loss: 0.4702 - accuracy: 0.7699
Epoch 91/110
804/804 [==============================] - 3s 3ms/step - loss: 0.4696 - accuracy: 0.7690
Epoch 92/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4697 - accuracy: 0.7680
Epoch 93/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4692 - accuracy: 0.7685
Epoch 94/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4696 - accuracy: 0.7685
Epoch 95/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4695 - accuracy: 0.7699
Epoch 96/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4695 - accuracy: 0.7689
Epoch 97/110
804/804 [==============================] - 2s 3ms/step - loss: 0.4693 - accuracy: 0.7693
Epoch 98/110
804/804 [==============================] - 3s 3ms/step - loss: 0.4688 - accuracy: 0.7699
Epoch 99/110
804/804 [==============================] - 2s 3ms/step - loss: 0.4692 - accuracy: 0.7698
Epoch 100/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4690 - accuracy: 0.7693
Epoch 101/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4687 - accuracy: 0.7692
Epoch 102/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4688 - accuracy: 0.7688
Epoch 103/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4690 - accuracy: 0.7691
Epoch 104/110
804/804 [==============================] - 2s 3ms/step - loss: 0.4696 - accuracy: 0.7694
Epoch 105/110
804/804 [==============================] - 3s 3ms/step - loss: 0.4692 - accuracy: 0.7692
Epoch 106/110
804/804 [==============================] - 2s 3ms/step - loss: 0.4689 - accuracy: 0.7701
Epoch 107/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4689 - accuracy: 0.7694
Epoch 108/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4687 - accuracy: 0.7694
Epoch 109/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4683 - accuracy: 0.7692
Epoch 110/110
804/804 [==============================] - 2s 2ms/step - loss: 0.4688 - accuracy: 0.7691

In [24]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5235 - accuracy: 0.7530 - 557ms/epoch - 2ms/step
Loss: 0.5235065221786499, Accuracy: 0.753002941608429

In [25]:
# Export our model to HDF5 file
from google.colab import files

nn_model.save('/h5/AlphabetSoupCharity_Optimization.h5')
files.download('/h5/AlphabetSoupCharity_Optimization.h5')