## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

In [2]:
#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN','NAME'], axis=1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Determine the number of unique values in each column.
unique_values = application_df.nunique()
unique_values

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
from pandas.core.arrays.interval import value_counts
# Look at APPLICATION_TYPE value counts for binning

app_counts = application_df['APPLICATION_TYPE'].value_counts()
app_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`


application_types_to_replace = list(app_counts[app_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts[classification_counts > 1]
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_counts[classification_counts < 700].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
numeric_dummies = pd.get_dummies(application_df)

In [11]:
numeric_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [12]:
# Split our preprocessed data into our features and target arrays
y = numeric_dummies['IS_SUCCESSFUL'].values

X = numeric_dummies.drop(columns='IS_SUCCESSFUL').values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1)

In [13]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [14]:
X_train_scaled.shape

(25724, 44)

## Compile, Train and Evaluate the Model

In [15]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
num_input_features = X_train_scaled.shape[1]
print(f"num_input_features : {num_input_features}")
# num of input features is 44 and multiple (2 or 3) of input feature is 88-132 so chose 80 for the first hidden node
hidden_node_1 = 80
hidden_node_2 = 30

nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_node_1, activation="relu", input_dim=num_input_features))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_node_2, activation="relu"))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

num_input_features : 44
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3600

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 6,061
Trainable params: 6,061
Non-trainable params: 0
_________________________________________________________________

In [16]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [17]:
# Train the model
fit_model = nn_model.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 5s 4ms/step - loss: 0.5688 - accuracy: 0.7236
Epoch 2/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5542 - accuracy: 0.7285
Epoch 3/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5516 - accuracy: 0.7299
Epoch 4/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5489 - accuracy: 0.7323
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5474 - accuracy: 0.7316
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7311
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7323
Epoch 8/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7327
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7335
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5445 - accuracy: 0.7341
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7324
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7355
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7345
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7334
Epoch 15/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7346
Epoch 16/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7349
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7345
Epoch 18/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7358
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7354
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7349
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7365
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7368
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7362
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7368
Epoch 25/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7366
Epoch 26/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7377
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7362
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7365
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7364
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7368
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7378
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7367
Epoch 33/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7374
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7385
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7369
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7364
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7375
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7374
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7369
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7381
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7371
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7383
Epoch 43/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7384
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7383
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7379
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7382
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5379 - accuracy: 0.7389
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7383
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7378
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5374 - accuracy: 0.7384
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7377
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7386
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7383
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5370 - accuracy: 0.7380
Epoch 55/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5371 - accuracy: 0.7387
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7382
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7382
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5368 - accuracy: 0.7382
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5369 - accuracy: 0.7396
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7393
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7386
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7391
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7400
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7386
Epoch 65/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7384
Epoch 66/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7395
Epoch 67/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7385
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7395
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7401
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7393
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7401
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7395
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7394
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7383
Epoch 75/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5360 - accuracy: 0.7402
Epoch 76/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7385
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7388
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7393
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7386
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7388
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7390
Epoch 82/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7392
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7396
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7388
Epoch 85/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7396
Epoch 86/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7396
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7384
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7400
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7394
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7400
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7402
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7406
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7392
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7399
Epoch 95/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7392
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7402
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7393
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7394
Epoch 99/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7396
Epoch 100/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7397

In [18]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5531 - accuracy: 0.7294 - 470ms/epoch - 2ms/step
Loss: 0.553102970123291, Accuracy: 0.7294460535049438

In [19]:
# Export our model to HDF5 file
from google.colab import files

nn_model.save("/h5/AlphabetSoupCharity.h5")
files.download ("/h5/AlphabetSoupCharity.h5")